name: .NET Backend CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore backend projects
        run: |
          dotnet restore RoomBooker.Core/RoomBooker.Core.csproj
          dotnet restore RoomBooker.Infrastructure/RoomBooker.Infrastructure.csproj
          dotnet restore RoomBooker.Api/RoomBooker.Api.csproj
          dotnet restore RoomBooker.Tests/RoomBooker.Tests.csproj

      - name: Build backend
        run: |
          dotnet build RoomBooker.Core/RoomBooker.Core.csproj --configuration Release --no-restore
          dotnet build RoomBooker.Infrastructure/RoomBooker.Infrastructure.csproj --configuration Release --no-restore
          dotnet build RoomBooker.Api/RoomBooker.Api.csproj --configuration Release --no-restore
          
      - name: Run tests
        run: dotnet test RoomBooker.Tests/RoomBooker.Tests.csproj --configuration Release --no-build
